In [1]:
import pandas as pd

In [2]:
ls

data.ipynb     fredgraph.csv

In [3]:
df = pd.read_csv("fredgraph.csv")
df

          DATE  LNS11300001_NBD20200101  LNS11300002_NBD20200101
0   2019-11-01                100.14451                 99.48187
1   2019-12-01                100.00000                 99.82729
2   2020-01-01                100.00000                100.00000
3   2020-02-01                 99.71098                100.17271
4   2020-03-01                 98.84393                 98.79102
5   2020-04-01                 95.37572                 94.30052
6   2020-05-01                 96.38728                 95.33679
7   2020-06-01                 97.39884                 96.71848
8   2020-07-01                 97.25434                 96.89119
9   2020-08-01                 97.97688                 96.71848
10  2020-09-01                 97.68786                 96.20035
11  2020-10-01                 97.97688                 96.54577
12  2020-11-01                 97.54335                 96.54577
13  2020-12-01                 97.54335                 96.71848
14  2021-01-01                 97.25434                 96.20035
15  2021-02-01                 97.10983                 96.54577
16  2021-03-01                 96.96532                 97.06390
17  2021-04-01                 97.68786                 96.89119
18  2021-05-01                 97.54335                 96.54577
19  2021-06-01                 97.83237                 96.89119
20  2021-07-01                 97.97688                 96.89119
21  2021-08-01                 97.97688                 96.89119
22  2021-09-01                 97.97688                 96.71848
23  2021-10-01                 97.97688                 96.89119
24  2021-11-01                 98.12139                 97.23661
25  2021-12-01                 97.97688                 97.58204
26  2022-01-01                 97.97688                 98.10017
27  2022-02-01                 98.26590                 97.92746
28  2022-03-01                 98.26590                 98.27288
29  2022-04-01                 98.12139                 97.92746
30  2022-05-01                 98.26590                 98.27288
31  2022-06-01                 98.12139                 98.10017
32  2022-07-01                 97.83237                 98.10017
33  2022-08-01                 98.12139                 98.61831
34  2022-09-01                 98.41040                 98.10017
35  2022-10-01                 98.55491                 97.75475
36  2022-11-01                 98.26590                 97.58204
37  2022-12-01                 98.41040                 98.10017
38  2023-01-01                 98.12139                 98.61831
39  2023-02-01                 98.26590                 98.79102
40  2023-03-01                 98.69942                 98.79102
41  2023-04-01                 98.26590                 98.96373
42  2023-05-01                 98.41040                 98.96373
43  2023-06-01                 98.41040                 98.96373
44  2023-07-01                 98.26590                 99.13644
45  2023-08-01                 98.55491                 99.48187
46  2023-09-01                 98.69942                 99.30915
47  2023-10-01                 98.26590                 99.48187
48  2023-11-01                 98.84393                 99.13644
49  2023-12-01                 98.41040                 98.61831
50  2024-01-01                 98.12139                 99.30915
51  2024-02-01                 97.83237                 99.48187
52  2024-03-01                 98.26590                 99.48187
53  2024-04-01                 98.12139                 99.65458
54  2024-05-01                 97.97688                 99.48187
55  2024-06-01                 98.41040                 98.96373
56  2024-07-01                 98.55491                 99.30915
57  2024-08-01                 98.12139                 99.82729
58  2024-09-01                 98.41040                 99.48187

In [4]:
df = df.rename(columns={
    'DATE': 'Date',
    'LNS11300001_NBD20200101': 'Men',
    'LNS11300002_NBD20200101': 'Women'
})
df

          Date        Men      Women
0   2019-11-01  100.14451   99.48187
1   2019-12-01  100.00000   99.82729
2   2020-01-01  100.00000  100.00000
3   2020-02-01   99.71098  100.17271
4   2020-03-01   98.84393   98.79102
5   2020-04-01   95.37572   94.30052
6   2020-05-01   96.38728   95.33679
7   2020-06-01   97.39884   96.71848
8   2020-07-01   97.25434   96.89119
9   2020-08-01   97.97688   96.71848
10  2020-09-01   97.68786   96.20035
11  2020-10-01   97.97688   96.54577
12  2020-11-01   97.54335   96.54577
13  2020-12-01   97.54335   96.71848
14  2021-01-01   97.25434   96.20035
15  2021-02-01   97.10983   96.54577
16  2021-03-01   96.96532   97.06390
17  2021-04-01   97.68786   96.89119
18  2021-05-01   97.54335   96.54577
19  2021-06-01   97.83237   96.89119
20  2021-07-01   97.97688   96.89119
21  2021-08-01   97.97688   96.89119
22  2021-09-01   97.97688   96.71848
23  2021-10-01   97.97688   96.89119
24  2021-11-01   98.12139   97.23661
25  2021-12-01   97.97688   97.58204
26  2022-01-01   97.97688   98.10017
27  2022-02-01   98.26590   97.92746
28  2022-03-01   98.26590   98.27288
29  2022-04-01   98.12139   97.92746
30  2022-05-01   98.26590   98.27288
31  2022-06-01   98.12139   98.10017
32  2022-07-01   97.83237   98.10017
33  2022-08-01   98.12139   98.61831
34  2022-09-01   98.41040   98.10017
35  2022-10-01   98.55491   97.75475
36  2022-11-01   98.26590   97.58204
37  2022-12-01   98.41040   98.10017
38  2023-01-01   98.12139   98.61831
39  2023-02-01   98.26590   98.79102
40  2023-03-01   98.69942   98.79102
41  2023-04-01   98.26590   98.96373
42  2023-05-01   98.41040   98.96373
43  2023-06-01   98.41040   98.96373
44  2023-07-01   98.26590   99.13644
45  2023-08-01   98.55491   99.48187
46  2023-09-01   98.69942   99.30915
47  2023-10-01   98.26590   99.48187
48  2023-11-01   98.84393   99.13644
49  2023-12-01   98.41040   98.61831
50  2024-01-01   98.12139   99.30915
51  2024-02-01   97.83237   99.48187
52  2024-03-01   98.26590   99.48187
53  2024-04-01   98.12139   99.65458
54  2024-05-01   97.97688   99.48187
55  2024-06-01   98.41040   98.96373
56  2024-07-01   98.55491   99.30915
57  2024-08-01   98.12139   99.82729
58  2024-09-01   98.41040   99.48187

In [14]:
print("Current date column type:", df['Date'].dtype)

Current date column type: object

In [15]:
df['Date'] = pd.to_datetime(df['Date'])
print("\nAfter conversion type:", df['Date'].dtype)

After conversion type: datetime64[ns]

In [16]:
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')
df

          Date        Men      Women
0   2019-11-01  100.14451   99.48187
1   2019-12-01  100.00000   99.82729
2   2020-01-01  100.00000  100.00000
3   2020-02-01   99.71098  100.17271
4   2020-03-01   98.84393   98.79102
5   2020-04-01   95.37572   94.30052
6   2020-05-01   96.38728   95.33679
7   2020-06-01   97.39884   96.71848
8   2020-07-01   97.25434   96.89119
9   2020-08-01   97.97688   96.71848
10  2020-09-01   97.68786   96.20035
11  2020-10-01   97.97688   96.54577
12  2020-11-01   97.54335   96.54577
13  2020-12-01   97.54335   96.71848
14  2021-01-01   97.25434   96.20035
15  2021-02-01   97.10983   96.54577
16  2021-03-01   96.96532   97.06390
17  2021-04-01   97.68786   96.89119
18  2021-05-01   97.54335   96.54577
19  2021-06-01   97.83237   96.89119
20  2021-07-01   97.97688   96.89119
21  2021-08-01   97.97688   96.89119
22  2021-09-01   97.97688   96.71848
23  2021-10-01   97.97688   96.89119
24  2021-11-01   98.12139   97.23661
25  2021-12-01   97.97688   97.58204
26  2022-01-01   97.97688   98.10017
27  2022-02-01   98.26590   97.92746
28  2022-03-01   98.26590   98.27288
29  2022-04-01   98.12139   97.92746
30  2022-05-01   98.26590   98.27288
31  2022-06-01   98.12139   98.10017
32  2022-07-01   97.83237   98.10017
33  2022-08-01   98.12139   98.61831
34  2022-09-01   98.41040   98.10017
35  2022-10-01   98.55491   97.75475
36  2022-11-01   98.26590   97.58204
37  2022-12-01   98.41040   98.10017
38  2023-01-01   98.12139   98.61831
39  2023-02-01   98.26590   98.79102
40  2023-03-01   98.69942   98.79102
41  2023-04-01   98.26590   98.96373
42  2023-05-01   98.41040   98.96373
43  2023-06-01   98.41040   98.96373
44  2023-07-01   98.26590   99.13644
45  2023-08-01   98.55491   99.48187
46  2023-09-01   98.69942   99.30915
47  2023-10-01   98.26590   99.48187
48  2023-11-01   98.84393   99.13644
49  2023-12-01   98.41040   98.61831
50  2024-01-01   98.12139   99.30915
51  2024-02-01   97.83237   99.48187
52  2024-03-01   98.26590   99.48187
53  2024-04-01   98.12139   99.65458
54  2024-05-01   97.97688   99.48187
55  2024-06-01   98.41040   98.96373
56  2024-07-01   98.55491   99.30915
57  2024-08-01   98.12139   99.82729
58  2024-09-01   98.41040   99.48187

In [17]:
print("\nSample of formatted dates:")
print(df['Date'].head())

Sample of formatted dates:
0    2019-11-01
1    2019-12-01
2    2020-01-01
3    2020-02-01
4    2020-03-01
Name: Date, dtype: object